import React from 'react'

function Footer() {
  return (
    <div className="mt-16 py-6 border-t border-gray-100 text-center">
      <p className="text-xs text-gray-400">AI Travel Planner — itineraries generated by AI, verify details before booking.</p>
    </div>
  )
}

export default Footer
